name: buildx

on:
  push:
    branches:
      - master
      - o
  pull_request:
    branches:
      - master
      - o

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      -
        name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

      -
        name: Build
        run: |
          docker build . # will run buildx
#   codecov:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-go@v2
#         with:
#           go-version: 1.14
#       - run: |
#           go test -v -coverprofile=coverage.out -covermode=atomic ./...
#       - name: Upload Coverage
#         uses: codecov/codecov-action@v2.1.0
#         with:
#           file: ./coverage.out
#           fail_ci_if_error: true
#           verbose: true
